/**
 * Created by eugeneseah on 25/10/16.
 */
const ReferenceName = {

    //GameUI
    Base : "#Base.png",
    IncreaseCannon : "#plus.png",
    IncreaseCannon_Down : "#PlusDw.png",
    DecreaseCannon : "#Minus.png",
    DecreaseCannon_Down : "#MinusDw.png",
    CannonPower : "#CoinDeck.png",
    CoinIcon : "#CoinIcon.png",
    CoinStackCoin : "#DeckCoins.png",
    PlayerIcon : "#PlayerIcon.png",
    OtherPlayerIcon : "#PlayerIcon2.png",
    ChangeSeatButton : "ChangeSitUP.png",
    ChangeSeatButtonDown : "ChangeSitDW.png",
    PlayerSeatIndicator : "#YouAreHere.png",
    LockOnButtonSide : "LockOnSide_",
    LockOnButtonBottom : "LockOnBtm_",
    LockOnButtonBackground : "#LOBase.png",
    LockOnButtonSlider : "LOCircle.png",
    LockOnButtonIndicatorGreen : "LOIconGreen.png",
    LockOnButtonIndicatorWhite : "LOIconWhite.png",
    LockOnButtonLock : "LOLock",
    LockOnButtonRelease : "LORelease",
    LockOnButtonGreen : "Green",
    LockOnButtonWhite : "White",
    LockOnButtonHorizontal : "H",
    LockOnButtonVertical : "V",
    LockOnTargetCrosshair :"#LockOnIcon_00000.png",

    BackButton : "Back.png",
    BackButtonOnPress : "BackDW.png",
    BackButtonText : "#BackChinese.png",

    LoadingIconAnim: "LoadingIcon_",
    LoadingIcon_00000: "#LoadingIcon_00000.png",

    CoinExplosionEffect : "CoinExplosion1_",
    ExplosionEffect : "Explosion_",
    LightEffect : "Explosion1_",
    AwardEffect : "Rewardmedal_",

    //Free round
    FreeRoundExplosionEffect : "FREffect_",

    //Lobby
    LobbyBackground : "#LobbyBG1.png",
    ScrollArrow : "#Arrow.png",//
    BonusPlaceHolder : "#Bonus.png",//
    BuyButton : "#Buy.png",
    LobbyCoinsBG : "#CoinBase.png",
    LobbyCoinIcon : "#Coins.png",//
    // GameSelectBox : "#Game Frame.png",
    GameSelectBox : "Game Frame.png",
    Star : "#level Star.png",//
    LevelBG : "#Level Bar.png",
    MessageButton : "#Log.png",
    NameBG : "#PlayerNameBase.png",
    ProfileFrame : "#Profile Frame.png",
    ProfileImage : "#Profile Image.png",
    LobbySettingsButton : "#Lobby Setting.png",
    TopBg : "#Top Base.png",
    LobbyCaustics : "Caustic_",
    LeftGrass : "LeftGrass_",
    RightGrass : "RightGrass_",

    //SeatSelectionScene
    SeatBackgroundBottom: "#SSBTMBG.png",
    SeatBackBtn:"SSBack.png",
    SeatBackBtnSelected: "SSBackRO.png",
    SeatNotificationBar: "#SSnotificationBar.png",
    Seat1X: "#SS1X.png",
    Seat10X: "#SS10X.png",
    Seat100X: "#SS100X.png",
    SeatWoodBackground: "#SSWoodBG.png",
    SeatSoloChinese: "#SSSoloChinese.png",
    SeatMultiPlayerChinese: "#SSMultiplayerChinese.png",
    SeatTable: "#SSTable.png",
    SeatSoloPic: "#SSSoloPic.png",
    SeatMultiPlayerPic: "#SSMutiplayerPic.png",
    SeatChair: "#SSChair_00000.png",
    SeatChairGlow: "#SSChairGlow.png",
    SeatArrow: "#SSArrow.png",

    //Dolphin
    DolphinIcon : "#FishIcon.png",
    DolphinBubble : "#Bubble.png",
    DolphinTextName : "#FishText",
    DolphinTextExtension : ".png",

    //floating menu
    FloatingMenuButtonBackground : "MenuButtonIdle.png",
    FloatingMenuButtonBackgroundDown : "MenuButtonOnPress.png",
    FloatingMenuButtonSettingsIcon :"#SettingIcon.png",
    FloatingMenuButtonSettingsText : "#SettingChinese.png",
    FloatingMenuButtonGameLogIcon : "#GamelogIcon.png",
    FloatingMenuButtonGameLogText : "#GamelogChinese.png",
    FloatingMenuButtonInfoIcon : "#InfoIcon.png",
    FloatingMenuButtonInfoText : "#InfoChinese.png",
    FloatingMenuButtonLeaderboardIcon : "#RankingIcon.png",
    FloatingMenuButtonLeaderboardText : "#RankingChinese.png",
    FloatingMenuButtonFAQIcon : "#GameFAQIcon.png",
    FloatingMenuButtonFAQText : "#GameFAQChinese.png",

    CrownIcon : "#Crown.png",

    //Floating menu shared
    FloatingTitleBackground : "#TitleBase2.png",
    FloatingBottomLeftDeco : "#Pattern1.png",
    FloatingPopupBackground : "#PopupBase2.png",
    FloatingCloseButton : "#CloseIcon.png",
    FloatingCloseButtonBackground : "CloseIdle.png",
    FloatingCloseButtonBackgroundOnPress : "CloseOnPress.png",

    //Jackpot
    JackpotBackground : "#JackpotIcon.png",
    JackpotShadow : "#JackpotDropShadow.png",
    JackpotBar : "#JackpotBar.png",
    JackpotBarFrame : "#JackpotBarFrame.png",
    JackpotLight : "#JackpotLightray.png",
    JackpotTitleChinese : "#JackpotChineseTitle.png",

    JackpotPopBase: "#JPPOPBase.png",
    JackpotPopFrame: "#JPPOPFrame.png",
    JackpotPopGold: "#JPPOPGold.png",
    JackpotPopSilver: "#JPPOPSilver.png",
    JackpotPopGreen: "#JPPOPGreen.png",
    JackpotPopBlue: "#JPPOPBlue.png",

    JackpotWaterCaustic00000: "#Caustic_00000.png",
    JackpotWaterCausticAnim: "Caustic_",

    JackpotLensFlareSmall : "#Lensflare3.png",
    JackpotLensFlareMedium : "#Lensflare2.png",
    JackpotLensFlareLarge : "#Lensflare1.png",

    //Leaderboard
    LeaderboardTextBackground : "#TextBG2.png",
    LeaderboardTitleChinese : "#RankingChineseTitle.png",
    LeaderboardTitlePlayerNameChinese : "#PlayernameChinese.png",
    LeaderboardTitleOnlineTimeChinese : "#OnlineTimeChinese.png",
    LeaderboardTitleScoreChinese : "#TodayScoreChinese.png",
    LeaderboardItemBackground : "#TextBG7.png",
    LeaderboardItemRankBackground : "#RankBase.png",

    //FAQ
    FAQTextBackground : "#TextBG3.png",
    FAQTitleChinese : "#GameFAQChineseTitle.png",
    FAQUserAgreementTitleChinese : "#UserAgreementChinese.png",
    FAQTabTitleChinese : "#GameFAQChinese (2).png",
    FAQTabBackground : "Button2Idle.png",
    FAQTabBackgroundOnPress : "Button2OnPress.png",
    FAQButtonBackground : "Button3Idle.png",
    FAQButtonBackgroundOnPress : "Button3OnPress.png",
    FAQGameRulesButtonText : "#GamerulesChinese.png",
    FAQUIFaqButtonText : "#UIControlChinese.png",
    FAQFishInfoButtonText : "#FishInfoChinese.png",
    FAQCannonInfoButtonText :"#CannonInfoChinese.png",
    FAQJackpotInfoButtonText : "#JackpotInfoChinese.png",

    FAQGreenBackground: "#background-bonus.png",
    FAQCannonInfoDisplay : "#Cannon-screenshot.png",
    FAQFishDisplay : "#fish.png",
    FAQLightGreenBackground : "#background-fish.png",
    FAQUiFaqDisplay : "#interface-screenshot.png",
    FAQJackpotDisplay : "#jackpot-screenshot.png",
    FAQFreeRoundDisplay : "#bonus-screenshot.png",
    FAQJackpotBackground : "#background-bonus.png",
    FAQJackpotSubtitleText : "#jackpot-subtitle.png",
    FAQFreeGameSubtitleText : "#bonus-subtitle.png",

    //Settings
    SettingsBackground : "#PopupBase1.png",
    SettingsTitleChinese : "#SettingChineseTitle.png",
    SettingsTitleBackground : "#TitleBase1.png",
    SettingsButtonBackground : "Button1Idle.png",
    SettingsButtonBackgroundOnPress : "Button1OnPress.png",
    SettingsSliderBackground : "#BarBase1.png",
    SettingsSliderFiller : "#BarMid1.png",
    SettingsSliderIndicator : "#Puller.png",
    SettingsMusicTitleChinese : "#BGMChinese.png",
    SettingsSoundTitleChinese : "#MusicFxChinese.png",
    SettingsGameLanguageSelectionTitleChinese : "#GameLangChinese.png",
    SettingsGameLanguageSelectionBar : "#BarBase2.png",
    SettingsDropDownButton : "DropDWIdle.png",
    SettingsDropDownButtonOnPress : "DropDWOnPress.png",
    SettingsConfirmButtonTextChinese : "#ConfirmChinese.png",
    SettingsCancelButtonTextChinese : "#CancelChinese.png",

    //Profile
    ProfileTitleChinese : "#InfoChineseTitle.png",
    ProfileUserTextBackground : "#TextBG6.png",
    ProfileNicknameTitleChinese : "#NicknameChinese.png",
    ProfileInputBackground : "#InputBox.png",
    ProfileEditButton : "EditButton.png",
    ProfileUsernameTitleChinese : "#UsernameChinese.png",
    ProfileIconBackground : "#SymbolBG.png",
    ProfileIconTextBackground : "#TextBG5.png",
    ProfileTimeIcon : "#TimeSymbol.png",
    ProfileCoinIcon : "#CoinsSymbol.png",
    ProfileRankingIcon : "#RankingSymbol.png",
    ProfileCoinStackIcon : "#Coin2weekSymbol.png",

    //GameLog
    GameLogTitleChinese : "#GamelogChineseTitle.png",
    GameLogRecordTabChinese : "#GameRecordChinese.png",
    GameLogConsumptionTabChinese : "#ConsumptionRecordChinese.png",
    GameLogRadioButton : "SelectionBase.png",
    GameLogRadioButtonSelected : "Selection.png",
    GameLogLogTitleBackground : "#TextHeaderBase.png",
    GameLogLogBackground : "#TextBG4.png",
    GameLogItemHighLight : "#TextBG4HL.png",
    GameLogRechargeTitleDateChinese : "#DateChinese.png",
    GameLogRechargeTitleTypeChinese : "#TypeChinese.png",
    GameLogRechargeTitleIdChinese : "#SerialNumberChinese.png",
    GameLogRechargeTitleAmountChinese : "#GoldAmountChinese.png",
    GameLogRechargeTitleTotalScoreChinese : "#PointChinese.png",
    GameLogConsumptionTitleIdChinese : "#NumberChinese.png",
    GameLogConsumptionTitleCannonAmountChinese : "#CannonPointChinese.png",
    GameLogConsumptionTitleProfitChinese : "#PointChinese.png",
    GameLogConsumptionTitleSceneNameChinese : "#StageChinese.png",
    GameLogConsumptionTitleFishAffectedChinese : "#FishChinese.png",
    GameLogConsumptionTitleFishCatchIndicatorChinese : "#CaptureChinese.png",
    GameLogConsumptionTitleFishCaughtIndicator : "#YesIcon.png",
    GameLogConsumptionTitleFishUncaughtIndicator : "#NoIcon.png",
    GameLogRadioTextPeriodShortChinese : "#TodayChinese.png",
    GameLogRadioTextPeriodMediumChinese :"#3DaysChinese.png",
    GameLogRadioTextPeriodLongChinese :"#2WeeksChinese.png",
    GameLogListSeparator : "#LineLong.png",
    GameLogListSeparatorShort : "#LineShort.png",
    GameLogRoundIdTitleChinese : "#RoundChinese.png",
    GameLogTotalSpendTitleChinese : "#CannonTotalPointChinese.png",
    GameLogTotalRevenueTitleChinese : "#FishPointChinese.png",
    GameLogTotalProfitTitleChinese : "#ProfitPointChinese.png",
    GameLogStartTimeTitleChinese : "#StartTimeChinese.png",
    GameLogEndTimeTitleChinese : "#EndTimeChinese.png",

    //Scoreboard
    ScoreboardBG : "#SummaryBase.png",
    CannonIcon : "#Cannon shot.png",
    CoinSpentIcon : "#Coin Spend.png",
    CoinEarnedIcon : "#Coins earn.png",
    GoldenFishIcon : "#GoldenFish.png",
    HitRateIcon : "#Hit rate.png",
    MultiCatchIcon : "#Multi Caught.png",
    SkillUsedButton : "#Skill uses.png",
    BottomScrollBarBG : "#BrownTransBGBox.png",
    TimeSpentIcon : "#Time play.png",
    TotalFishIcon : "#TotalFish.png",
    InfoSlotBG : "#Yellow Bar.png",
    PlayButton : "#GreenButton.png",
    LobbyButton : "#RedButton.png",

    //SideMenu
    SideMenuBG : "#SideMenu.png",
    SideMenuSettingsButton : "#Setting.png",
    SideMenuFishListButton : "#Fishes.png",
    SideMenuExitButton : "#Exit.png",

    //BottomMenu
    BottomMenuButton : "#Option.png",
    BottomMenuSettingsButton : "#Setting V2.png",
    BottomMenuFishListButton : "#Fish V2.png",
    BottomMenuExitButton : "#Exit V2.png",

    //jackpot
    JackpotBase: "#JPBase.png",
    JackpotTimerBg: "#TimerBackground.png",
    JackpotTimerIcon: "#TimerIcon.png",
    JackpotTitle: "#JPTitle.png",
    JackpotPrizeListFrame: "#PrizeListFrame.png",
    JackpotMermaidIcon: "#MermaidIcon.png",
    JackpotSharkIcon:"#SharkIcon.png",
    JackpotTurtleIcon: "#TurtleIcon.png",
    JackpotButterflyFishIcon: "#ButterflyfishIcon.png",
    JackpotNotificationBackground: "#NotificationBackground.png",
    JackpotTreasureBoxOpen_00000: "#TreasureBoxOpen_00000.png",
    JackpotTreasureBoxOpenAnm: "TreasureBoxOpen_",
    JackpotButterflyFishMedal_00000: "#JPButterflyFishMedal_00000.png",
    JackpotButterflyFishMedalAnm: "JPButterflyFishMedal_",
    JackpotMermaidMedal_00000: "#JPMermaidMedal_00000.png",
    JackpotMermaidMedalAnm: "JPMermaidMedal_",
    JackpotSharkMedal_00000: "#JPSharkMedal_00000.png",
    JackpotSharkMedalAnm: "JPSharkMedal_",
    JackpotTurtleMedal_00000: "#JPTurtleMedal_00000.png",
    JackpotTurtleMedalAnm: "JPTurtleMedal_",
    JackpotChestGlow: "#ChestGlow.png",
    JackpotCoinAnimation_00001: "#JPCoinAnimation_00001.png",
    JackpotCoinAnimation: "JPCoinAnimation_",
    JackpotCoinLight: "#JPCoinLight.png",
    JackpotWinBase: "#JPWinBase.png",
    JackpotWin1: "#JPWin1.png",
    JackpotWin2: "#JPWin2.png",
    JackpotWin3: "#JPWin3.png",
    JackpotWin4: "#JPWin4.png",
    JackpotMermaidIconGray: "#MermaidIconGray.png",
    JackpotSharkIconGray: "#SharkIconGray.png",
    JackpotTurtleIconGray: "#TurtleIconGray.png",
    JackpotButterflyFishIconGray: "#ButterflyfishIconGray.png",
    JackpotMermaidMedalGlow: "#JPMermaidMedalGlow.png",
    JackpotSharkMedalGlow: "#JPSharkMedalGlow.png",
    JackpotTurtleMedalGlow: "#JPTurtleMedalGlow.png",
    JackpotButterflyFishMedalGlow: "#JPButterflyFishMedalGlow.png",

    //OptionsMenu
    OptionsBG : "#Setting BG.png",
    OptionBarBG : "#Setting Bar Full.png",
    OptionsBarNegative : "#Setting Bar Empty.png",
    FishSliderButton : "#Setting Slider Button.png",


    //------------
    //Localisable
    //------------
    //@TODO: move to seperate file

    //Login
    LoginNamePlaceHolder : "Email",
    LoginPassPlaceHolder : "Password",

    //Scoreboard
    SessionTime : "Session Time",
    GoldSpent : "Gold Spent",
    GoldEarned : "Gold Earned",
    FishCaught : "Fish Caught",
    GoldenFishCaught : "Golden Fish Caught",
    MultiCatch : "Multi-Catches",
    BulletsFired : "Bullets Fired",
    SkillsUsed : "Skills Used",
    ReturnRate : "Return Rate",
    GoToLobby : "Lobby",
    GoToNewGame : "Play",

    //lobby
    LobbyBuyButton : "Buy",

};